### ISSUE TITLE
Allow users to create multiple budgets

### ISSUE THREAD

**Issue by truongnguyenlinh** [icextreme/fintrack#14]
# Overview
Currently, users have access to only 1 budget list, where they can add entries.

Refactor the DB to make it so that users can select their different budgets, to add their record entries. 

<img width="416" alt="Screen Shot 2022-03-30 at 1 44 52 AM" src="https://user-images.githubusercontent.com/46574403/160790997-55d8396b-a9a4-4fd6-b8d5-e7c093961b9d.png">

**Comment by icextreme** [comment]
![image](https://user-images.githubusercontent.com/74882450/161404672-77115dc5-1ecb-4935-84b5-211705186d1f.png)
