### ISSUE TITLE
Add models

### ISSUE THREAD

**Issue by icextreme** [icextreme/fintrack#5]
# Summary
- Create array of `spendings`
- Budget category Enum
- User class/model
- Categorize data (budget has a list of spendings, users own 1..+ budgets)
- Record (entry) 
- DB instantiation (Firebase)

**Comment by truongnguyenlinh** [comment]
# Overview
- Array of `spendings` is array of `records`
- User class completed, with attributes firstName, lastName, password and email
- Record class implemented for income/expense insertion
- DB instantiated using Firebase

# Todo
- Budget category enum
- Filtering of data based on auth user

**Comment by truongnguyenlinh** [comment]
Filtering complete on based on user auth, budget category enum included
